Repository Harkishen-Singh/Jarvis-personal-assistant, pull requests merged in 2020-03, with the labels that each got.

#147 Resolved issue #140
  view/index.html
Labels: beginner, gssoc20

#169 Added Achievements section
  README.md
Labels: easy, gssoc20

#170 Added meaning scraping using golang
  service/controllers/messages.go
Labels: gssoc20, hard

#171 Added weather scraping with golang
  service/controllers/messages.go
  view/desktop/app/templates/components/weather-view.html
  view/web/app-jarvis.js
  view/web/components/main.html
Labels: gssoc20, hard

#177 Added medicine scrapping with golang
  service/controllers/messages.go
  service/go.sum
  service/messages/health.go
  service/scrapper/common.go
Labels: gssoc20, hard

#176 Mockup for Home page UI
  ui-designs/ui-design--1.txt
Labels: gssoc20, medium

#179 Updated README.md with Postman doc link
  README.md
Labels: beginner, gssoc20

#180 Postman doc update
  README.md
Labels: beginner, gssoc20

#188 Added symptoms scrapping with golang
  service/messages/health.go
Labels: gssoc20, medium

#190 Saving logs on secondary storage
  .gitignore
  service/config/index.go
  service/controllers/messages.go
  service/controllers/send_mail.go
  service/controllers/subprocessHandler.go
  service/go.mod
  service/go.sum
  service/logger/index.go
  service/messages/conversations.go
  service/messages/health.go
  service/utils/Logs.go
  service/utils/service.go
Labels: gssoc20, medium

#194 Added image scrapping with golang
  service/controllers/messages.go
Labels: gssoc20, medium

#200 Setup continuous deployment for jarvis as a permanent service
  .travis.yml
  Makefile
  Procfile
  README.md
  audio/hello! whats up .mp3
  logs/index.log
  service/config/index.go
  service/controllers/messages_test.go
  service/heroku.yml
  service/maintut.go
  service/messages/about.md
  service/messages/conversations.go
  service/messages/health.go
  static/config.json
  static/health_symptoms.json
  static/health_symptoms_db.json
  static/medicine_database.json
  static/messages.json
  static/messages_replies.json
Labels: high priority

#204 Updated install.md file
  INSTALL.md
Labels: easy, gssoc20
